"""A script for generating lib/src/keycodes.dart."""

from pathlib import Path
from typing import Dict, List, Optional, TextIO

from bs4 import BeautifulSoup, Tag
from requests import Response, Session

http: Session = Session()


def get_dict(url: str, index: int) -> Dict[str, str]:
    """Return a dictionary containing keys.

    :param element: A table element to use.

    :param index: The index of the column to scan for key names.
    """
    r: Response = http.get(url)
    s: BeautifulSoup = BeautifulSoup(r.content, "lxml")
    element: Tag = s.find("table")
    d: Dict[str, str] = {}
    tr: Tag
    for tr in element.find_all("tr")[1:]:
        tds: List[Tag] = tr.find_all("td")
        name_td: Tag = tds[0]
        key_td: Tag = tds[index]
        key: str = key_td.text
        if not key.startswith("SDL"):
            continue
        name: str = name_td.text
        d[name] = key.lower()
    return d


def write_dict(f: TextIO, d: Dict[str, str]) -> None:
    """Write a dictionary out to a file as an enum.

    :param f: An open file.

    :param d: The dictionary to write.
    """
    name: str
    key: str
    for name, key in d.items():
        remove_prefix: str
        add_prefix: str = ""
        if key.startswith("sdl_"):
            remove_prefix = "sdl_"
        else:
            remove_prefix = "SDLK_"
            add_prefix = "keycode_"
        f.write(f"\n  /// {name}\n")
        f.write(f"  {add_prefix}{key[len(remove_prefix):]},\n")
    f.write("}\n")


if __name__ == "__main__":
    keycode_url: str = "https://wiki.libsdl.org/SDL_Keycode"
    scancode_url: str = "https://wiki.libsdl.org/SDL_Scancode"
    scancodes = get_dict(scancode_url, 1)
    keycodes = get_dict(keycode_url, 2)
    with open(Path("lib") / "src" / "keycodes.dart", "w") as f:
        f.write("/// Automatically generated by `generate-keys.py`.\n\n")
        f.write("/// Scancodes.\n///\n")
        f.write("/// [SDL Docs](https://wiki.libsdl.org/SDL_Scancode)\n")
        f.write("enum scancodes {")
        write_dict(f, scancodes)
        f.write("\n/// Keycodes.\n///\n")
        f.write("/// [SDL Docs](https://wiki.libsdl.org/SDL_Keycode)\n")
        f.write("enum keycodes {")
        write_dict(f, keycodes)
