name: dart_sdl
description: Dart bindings for SDL.
version: 0.0.5
homepage: https://github.com/chrisnorman7/dart_sdl

environment:
  sdk: '>=2.14.0-90.0.dev <3.0.0'

dependencies:
  ffi: ^1.0.0
  ffigen: ^3.1.0-dev.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

ffigen:
  output: "lib/src/sdl_bindings.dart"
  name: "DartSdl"
  description: "Bindings for SDL"
  headers:
    entry-points:
      - "SDL2-2.0.14/include/SDL.h"
      - "SDL2-2.0.14/include/SDL_hints.h"
      - "SDL2-2.0.14/include/SDL_error.h"
      - "SDL2-2.0.14/include/SDL_log.h"
      - "SDL2-2.0.14/include/SDL_assert.h"
      - "SDL2-2.0.14/include/SDL_version.h"
      - "SDL2-2.0.14/include/SDL_revision.h"
      - "SDL2-2.0.14/include/SDL_video.h"
      - "SDL2-2.0.14/include/SDL_clipboard.h"
      - "SDL2-2.0.14/include/SDL_events.h"
      - "SDL2-2.0.14/include/SDL_keyboard.h"
      - "SDL2-2.0.14/include/SDL_keycode.h"
      - "SDL2-2.0.14/include/SDL_scancode.h"
      - "SDL2-2.0.14/include/SDL_haptic.h"
