// ignore_for_file: constant_identifier_names
/// Automatically generated by `generate_keys.dart`.
import 'error.dart';
import 'sdl_bindings.dart';

/// Scancodes.
///
/// [SDL Docs](https://wiki.libsdl.org/SDL_Scancode)
enum ScanCode {
  /// SDL_SCANCODE_UNKNOWN
  SCANCODE_UNKNOWN,

  /// SDL_SCANCODE_A
  SCANCODE_A,

  /// SDL_SCANCODE_B
  SCANCODE_B,

  /// SDL_SCANCODE_C
  SCANCODE_C,

  /// SDL_SCANCODE_D
  SCANCODE_D,

  /// SDL_SCANCODE_E
  SCANCODE_E,

  /// SDL_SCANCODE_F
  SCANCODE_F,

  /// SDL_SCANCODE_G
  SCANCODE_G,

  /// SDL_SCANCODE_H
  SCANCODE_H,

  /// SDL_SCANCODE_I
  SCANCODE_I,

  /// SDL_SCANCODE_J
  SCANCODE_J,

  /// SDL_SCANCODE_K
  SCANCODE_K,

  /// SDL_SCANCODE_L
  SCANCODE_L,

  /// SDL_SCANCODE_M
  SCANCODE_M,

  /// SDL_SCANCODE_N
  SCANCODE_N,

  /// SDL_SCANCODE_O
  SCANCODE_O,

  /// SDL_SCANCODE_P
  SCANCODE_P,

  /// SDL_SCANCODE_Q
  SCANCODE_Q,

  /// SDL_SCANCODE_R
  SCANCODE_R,

  /// SDL_SCANCODE_S
  SCANCODE_S,

  /// SDL_SCANCODE_T
  SCANCODE_T,

  /// SDL_SCANCODE_U
  SCANCODE_U,

  /// SDL_SCANCODE_V
  SCANCODE_V,

  /// SDL_SCANCODE_W
  SCANCODE_W,

  /// SDL_SCANCODE_X
  SCANCODE_X,

  /// SDL_SCANCODE_Y
  SCANCODE_Y,

  /// SDL_SCANCODE_Z
  SCANCODE_Z,

  /// SDL_SCANCODE_1
  SCANCODE_1,

  /// SDL_SCANCODE_2
  SCANCODE_2,

  /// SDL_SCANCODE_3
  SCANCODE_3,

  /// SDL_SCANCODE_4
  SCANCODE_4,

  /// SDL_SCANCODE_5
  SCANCODE_5,

  /// SDL_SCANCODE_6
  SCANCODE_6,

  /// SDL_SCANCODE_7
  SCANCODE_7,

  /// SDL_SCANCODE_8
  SCANCODE_8,

  /// SDL_SCANCODE_9
  SCANCODE_9,

  /// SDL_SCANCODE_0
  SCANCODE_0,

  /// SDL_SCANCODE_RETURN
  SCANCODE_RETURN,

  /// SDL_SCANCODE_ESCAPE
  SCANCODE_ESCAPE,

  /// SDL_SCANCODE_BACKSPACE
  SCANCODE_BACKSPACE,

  /// SDL_SCANCODE_TAB
  SCANCODE_TAB,

  /// SDL_SCANCODE_SPACE
  SCANCODE_SPACE,

  /// SDL_SCANCODE_MINUS
  SCANCODE_MINUS,

  /// SDL_SCANCODE_EQUALS
  SCANCODE_EQUALS,

  /// SDL_SCANCODE_LEFTBRACKET
  SCANCODE_LEFTBRACKET,

  /// SDL_SCANCODE_RIGHTBRACKET
  SCANCODE_RIGHTBRACKET,

  /// SDL_SCANCODE_BACKSLASH
  SCANCODE_BACKSLASH,

  /// SDL_SCANCODE_NONUSHASH
  SCANCODE_NONUSHASH,

  /// SDL_SCANCODE_SEMICOLON
  SCANCODE_SEMICOLON,

  /// SDL_SCANCODE_APOSTROPHE
  SCANCODE_APOSTROPHE,

  /// SDL_SCANCODE_GRAVE
  SCANCODE_GRAVE,

  /// SDL_SCANCODE_COMMA
  SCANCODE_COMMA,

  /// SDL_SCANCODE_PERIOD
  SCANCODE_PERIOD,

  /// SDL_SCANCODE_SLASH
  SCANCODE_SLASH,

  /// SDL_SCANCODE_CAPSLOCK
  SCANCODE_CAPSLOCK,

  /// SDL_SCANCODE_F1
  SCANCODE_F1,

  /// SDL_SCANCODE_F2
  SCANCODE_F2,

  /// SDL_SCANCODE_F3
  SCANCODE_F3,

  /// SDL_SCANCODE_F4
  SCANCODE_F4,

  /// SDL_SCANCODE_F5
  SCANCODE_F5,

  /// SDL_SCANCODE_F6
  SCANCODE_F6,

  /// SDL_SCANCODE_F7
  SCANCODE_F7,

  /// SDL_SCANCODE_F8
  SCANCODE_F8,

  /// SDL_SCANCODE_F9
  SCANCODE_F9,

  /// SDL_SCANCODE_F10
  SCANCODE_F10,

  /// SDL_SCANCODE_F11
  SCANCODE_F11,

  /// SDL_SCANCODE_F12
  SCANCODE_F12,

  /// SDL_SCANCODE_PRINTSCREEN
  SCANCODE_PRINTSCREEN,

  /// SDL_SCANCODE_SCROLLLOCK
  SCANCODE_SCROLLLOCK,

  /// SDL_SCANCODE_PAUSE
  SCANCODE_PAUSE,

  /// SDL_SCANCODE_INSERT
  SCANCODE_INSERT,

  /// SDL_SCANCODE_HOME
  SCANCODE_HOME,

  /// SDL_SCANCODE_PAGEUP
  SCANCODE_PAGEUP,

  /// SDL_SCANCODE_DELETE
  SCANCODE_DELETE,

  /// SDL_SCANCODE_END
  SCANCODE_END,

  /// SDL_SCANCODE_PAGEDOWN
  SCANCODE_PAGEDOWN,

  /// SDL_SCANCODE_RIGHT
  SCANCODE_RIGHT,

  /// SDL_SCANCODE_LEFT
  SCANCODE_LEFT,

  /// SDL_SCANCODE_DOWN
  SCANCODE_DOWN,

  /// SDL_SCANCODE_UP
  SCANCODE_UP,

  /// SDL_SCANCODE_NUMLOCKCLEAR
  SCANCODE_NUMLOCKCLEAR,

  /// SDL_SCANCODE_KP_DIVIDE
  SCANCODE_KP_DIVIDE,

  /// SDL_SCANCODE_KP_MULTIPLY
  SCANCODE_KP_MULTIPLY,

  /// SDL_SCANCODE_KP_MINUS
  SCANCODE_KP_MINUS,

  /// SDL_SCANCODE_KP_PLUS
  SCANCODE_KP_PLUS,

  /// SDL_SCANCODE_KP_ENTER
  SCANCODE_KP_ENTER,

  /// SDL_SCANCODE_KP_1
  SCANCODE_KP_1,

  /// SDL_SCANCODE_KP_2
  SCANCODE_KP_2,

  /// SDL_SCANCODE_KP_3
  SCANCODE_KP_3,

  /// SDL_SCANCODE_KP_4
  SCANCODE_KP_4,

  /// SDL_SCANCODE_KP_5
  SCANCODE_KP_5,

  /// SDL_SCANCODE_KP_6
  SCANCODE_KP_6,

  /// SDL_SCANCODE_KP_7
  SCANCODE_KP_7,

  /// SDL_SCANCODE_KP_8
  SCANCODE_KP_8,

  /// SDL_SCANCODE_KP_9
  SCANCODE_KP_9,

  /// SDL_SCANCODE_KP_0
  SCANCODE_KP_0,

  /// SDL_SCANCODE_KP_PERIOD
  SCANCODE_KP_PERIOD,

  /// SDL_SCANCODE_NONUSBACKSLASH
  SCANCODE_NONUSBACKSLASH,

  /// SDL_SCANCODE_APPLICATION
  SCANCODE_APPLICATION,

  /// SDL_SCANCODE_POWER
  SCANCODE_POWER,

  /// SDL_SCANCODE_KP_EQUALS
  SCANCODE_KP_EQUALS,

  /// SDL_SCANCODE_F13
  SCANCODE_F13,

  /// SDL_SCANCODE_F14
  SCANCODE_F14,

  /// SDL_SCANCODE_F15
  SCANCODE_F15,

  /// SDL_SCANCODE_F16
  SCANCODE_F16,

  /// SDL_SCANCODE_F17
  SCANCODE_F17,

  /// SDL_SCANCODE_F18
  SCANCODE_F18,

  /// SDL_SCANCODE_F19
  SCANCODE_F19,

  /// SDL_SCANCODE_F20
  SCANCODE_F20,

  /// SDL_SCANCODE_F21
  SCANCODE_F21,

  /// SDL_SCANCODE_F22
  SCANCODE_F22,

  /// SDL_SCANCODE_F23
  SCANCODE_F23,

  /// SDL_SCANCODE_F24
  SCANCODE_F24,

  /// SDL_SCANCODE_EXECUTE
  SCANCODE_EXECUTE,

  /// SDL_SCANCODE_HELP
  SCANCODE_HELP,

  /// SDL_SCANCODE_MENU
  SCANCODE_MENU,

  /// SDL_SCANCODE_SELECT
  SCANCODE_SELECT,

  /// SDL_SCANCODE_STOP
  SCANCODE_STOP,

  /// SDL_SCANCODE_AGAIN
  SCANCODE_AGAIN,

  /// SDL_SCANCODE_UNDO
  SCANCODE_UNDO,

  /// SDL_SCANCODE_CUT
  SCANCODE_CUT,

  /// SDL_SCANCODE_COPY
  SCANCODE_COPY,

  /// SDL_SCANCODE_PASTE
  SCANCODE_PASTE,

  /// SDL_SCANCODE_FIND
  SCANCODE_FIND,

  /// SDL_SCANCODE_MUTE
  SCANCODE_MUTE,

  /// SDL_SCANCODE_VOLUMEUP
  SCANCODE_VOLUMEUP,

  /// SDL_SCANCODE_VOLUMEDOWN
  SCANCODE_VOLUMEDOWN,

  /// SDL_SCANCODE_KP_COMMA
  SCANCODE_KP_COMMA,

  /// SDL_SCANCODE_KP_EQUALSAS400
  SCANCODE_KP_EQUALSAS400,

  /// SDL_SCANCODE_INTERNATIONAL1
  SCANCODE_INTERNATIONAL1,

  /// SDL_SCANCODE_INTERNATIONAL2
  SCANCODE_INTERNATIONAL2,

  /// SDL_SCANCODE_INTERNATIONAL3
  SCANCODE_INTERNATIONAL3,

  /// SDL_SCANCODE_INTERNATIONAL4
  SCANCODE_INTERNATIONAL4,

  /// SDL_SCANCODE_INTERNATIONAL5
  SCANCODE_INTERNATIONAL5,

  /// SDL_SCANCODE_INTERNATIONAL6
  SCANCODE_INTERNATIONAL6,

  /// SDL_SCANCODE_INTERNATIONAL7
  SCANCODE_INTERNATIONAL7,

  /// SDL_SCANCODE_INTERNATIONAL8
  SCANCODE_INTERNATIONAL8,

  /// SDL_SCANCODE_INTERNATIONAL9
  SCANCODE_INTERNATIONAL9,

  /// SDL_SCANCODE_LANG1
  SCANCODE_LANG1,

  /// SDL_SCANCODE_LANG2
  SCANCODE_LANG2,

  /// SDL_SCANCODE_LANG3
  SCANCODE_LANG3,

  /// SDL_SCANCODE_LANG4
  SCANCODE_LANG4,

  /// SDL_SCANCODE_LANG5
  SCANCODE_LANG5,

  /// SDL_SCANCODE_LANG6
  SCANCODE_LANG6,

  /// SDL_SCANCODE_LANG7
  SCANCODE_LANG7,

  /// SDL_SCANCODE_LANG8
  SCANCODE_LANG8,

  /// SDL_SCANCODE_LANG9
  SCANCODE_LANG9,

  /// SDL_SCANCODE_ALTERASE
  SCANCODE_ALTERASE,

  /// SDL_SCANCODE_SYSREQ
  SCANCODE_SYSREQ,

  /// SDL_SCANCODE_CANCEL
  SCANCODE_CANCEL,

  /// SDL_SCANCODE_CLEAR
  SCANCODE_CLEAR,

  /// SDL_SCANCODE_PRIOR
  SCANCODE_PRIOR,

  /// SDL_SCANCODE_RETURN2
  SCANCODE_RETURN2,

  /// SDL_SCANCODE_SEPARATOR
  SCANCODE_SEPARATOR,

  /// SDL_SCANCODE_OUT
  SCANCODE_OUT,

  /// SDL_SCANCODE_OPER
  SCANCODE_OPER,

  /// SDL_SCANCODE_CLEARAGAIN
  SCANCODE_CLEARAGAIN,

  /// SDL_SCANCODE_CRSEL
  SCANCODE_CRSEL,

  /// SDL_SCANCODE_EXSEL
  SCANCODE_EXSEL,

  /// SDL_SCANCODE_KP_00
  SCANCODE_KP_00,

  /// SDL_SCANCODE_KP_000
  SCANCODE_KP_000,

  /// SDL_SCANCODE_THOUSANDSSEPARATOR
  SCANCODE_THOUSANDSSEPARATOR,

  /// SDL_SCANCODE_DECIMALSEPARATOR
  SCANCODE_DECIMALSEPARATOR,

  /// SDL_SCANCODE_CURRENCYUNIT
  SCANCODE_CURRENCYUNIT,

  /// SDL_SCANCODE_CURRENCYSUBUNIT
  SCANCODE_CURRENCYSUBUNIT,

  /// SDL_SCANCODE_KP_LEFTPAREN
  SCANCODE_KP_LEFTPAREN,

  /// SDL_SCANCODE_KP_RIGHTPAREN
  SCANCODE_KP_RIGHTPAREN,

  /// SDL_SCANCODE_KP_LEFTBRACE
  SCANCODE_KP_LEFTBRACE,

  /// SDL_SCANCODE_KP_RIGHTBRACE
  SCANCODE_KP_RIGHTBRACE,

  /// SDL_SCANCODE_KP_TAB
  SCANCODE_KP_TAB,

  /// SDL_SCANCODE_KP_BACKSPACE
  SCANCODE_KP_BACKSPACE,

  /// SDL_SCANCODE_KP_A
  SCANCODE_KP_A,

  /// SDL_SCANCODE_KP_B
  SCANCODE_KP_B,

  /// SDL_SCANCODE_KP_C
  SCANCODE_KP_C,

  /// SDL_SCANCODE_KP_D
  SCANCODE_KP_D,

  /// SDL_SCANCODE_KP_E
  SCANCODE_KP_E,

  /// SDL_SCANCODE_KP_F
  SCANCODE_KP_F,

  /// SDL_SCANCODE_KP_XOR
  SCANCODE_KP_XOR,

  /// SDL_SCANCODE_KP_POWER
  SCANCODE_KP_POWER,

  /// SDL_SCANCODE_KP_PERCENT
  SCANCODE_KP_PERCENT,

  /// SDL_SCANCODE_KP_LESS
  SCANCODE_KP_LESS,

  /// SDL_SCANCODE_KP_GREATER
  SCANCODE_KP_GREATER,

  /// SDL_SCANCODE_KP_AMPERSAND
  SCANCODE_KP_AMPERSAND,

  /// SDL_SCANCODE_KP_DBLAMPERSAND
  SCANCODE_KP_DBLAMPERSAND,

  /// SDL_SCANCODE_KP_VERTICALBAR
  SCANCODE_KP_VERTICALBAR,

  /// SDL_SCANCODE_KP_DBLVERTICALBAR
  SCANCODE_KP_DBLVERTICALBAR,

  /// SDL_SCANCODE_KP_COLON
  SCANCODE_KP_COLON,

  /// SDL_SCANCODE_KP_HASH
  SCANCODE_KP_HASH,

  /// SDL_SCANCODE_KP_SPACE
  SCANCODE_KP_SPACE,

  /// SDL_SCANCODE_KP_AT
  SCANCODE_KP_AT,

  /// SDL_SCANCODE_KP_EXCLAM
  SCANCODE_KP_EXCLAM,

  /// SDL_SCANCODE_KP_MEMSTORE
  SCANCODE_KP_MEMSTORE,

  /// SDL_SCANCODE_KP_MEMRECALL
  SCANCODE_KP_MEMRECALL,

  /// SDL_SCANCODE_KP_MEMCLEAR
  SCANCODE_KP_MEMCLEAR,

  /// SDL_SCANCODE_KP_MEMADD
  SCANCODE_KP_MEMADD,

  /// SDL_SCANCODE_KP_MEMSUBTRACT
  SCANCODE_KP_MEMSUBTRACT,

  /// SDL_SCANCODE_KP_MEMMULTIPLY
  SCANCODE_KP_MEMMULTIPLY,

  /// SDL_SCANCODE_KP_MEMDIVIDE
  SCANCODE_KP_MEMDIVIDE,

  /// SDL_SCANCODE_KP_PLUSMINUS
  SCANCODE_KP_PLUSMINUS,

  /// SDL_SCANCODE_KP_CLEAR
  SCANCODE_KP_CLEAR,

  /// SDL_SCANCODE_KP_CLEARENTRY
  SCANCODE_KP_CLEARENTRY,

  /// SDL_SCANCODE_KP_BINARY
  SCANCODE_KP_BINARY,

  /// SDL_SCANCODE_KP_OCTAL
  SCANCODE_KP_OCTAL,

  /// SDL_SCANCODE_KP_DECIMAL
  SCANCODE_KP_DECIMAL,

  /// SDL_SCANCODE_KP_HEXADECIMAL
  SCANCODE_KP_HEXADECIMAL,

  /// SDL_SCANCODE_LCTRL
  SCANCODE_LCTRL,

  /// SDL_SCANCODE_LSHIFT
  SCANCODE_LSHIFT,

  /// SDL_SCANCODE_LALT
  SCANCODE_LALT,

  /// SDL_SCANCODE_LGUI
  SCANCODE_LGUI,

  /// SDL_SCANCODE_RCTRL
  SCANCODE_RCTRL,

  /// SDL_SCANCODE_RSHIFT
  SCANCODE_RSHIFT,

  /// SDL_SCANCODE_RALT
  SCANCODE_RALT,

  /// SDL_SCANCODE_RGUI
  SCANCODE_RGUI,

  /// SDL_SCANCODE_MODE
  SCANCODE_MODE,

  /// SDL_SCANCODE_AUDIONEXT
  SCANCODE_AUDIONEXT,

  /// SDL_SCANCODE_AUDIOPREV
  SCANCODE_AUDIOPREV,

  /// SDL_SCANCODE_AUDIOSTOP
  SCANCODE_AUDIOSTOP,

  /// SDL_SCANCODE_AUDIOPLAY
  SCANCODE_AUDIOPLAY,

  /// SDL_SCANCODE_AUDIOMUTE
  SCANCODE_AUDIOMUTE,

  /// SDL_SCANCODE_MEDIASELECT
  SCANCODE_MEDIASELECT,

  /// SDL_SCANCODE_WWW
  SCANCODE_WWW,

  /// SDL_SCANCODE_MAIL
  SCANCODE_MAIL,

  /// SDL_SCANCODE_CALCULATOR
  SCANCODE_CALCULATOR,

  /// SDL_SCANCODE_COMPUTER
  SCANCODE_COMPUTER,

  /// SDL_SCANCODE_AC_SEARCH
  SCANCODE_AC_SEARCH,

  /// SDL_SCANCODE_AC_HOME
  SCANCODE_AC_HOME,

  /// SDL_SCANCODE_AC_BACK
  SCANCODE_AC_BACK,

  /// SDL_SCANCODE_AC_FORWARD
  SCANCODE_AC_FORWARD,

  /// SDL_SCANCODE_AC_STOP
  SCANCODE_AC_STOP,

  /// SDL_SCANCODE_AC_REFRESH
  SCANCODE_AC_REFRESH,

  /// SDL_SCANCODE_AC_BOOKMARKS
  SCANCODE_AC_BOOKMARKS,

  /// SDL_SCANCODE_BRIGHTNESSDOWN
  SCANCODE_BRIGHTNESSDOWN,

  /// SDL_SCANCODE_BRIGHTNESSUP
  SCANCODE_BRIGHTNESSUP,

  /// SDL_SCANCODE_DISPLAYSWITCH
  SCANCODE_DISPLAYSWITCH,

  /// SDL_SCANCODE_KBDILLUMTOGGLE
  SCANCODE_KBDILLUMTOGGLE,

  /// SDL_SCANCODE_KBDILLUMDOWN
  SCANCODE_KBDILLUMDOWN,

  /// SDL_SCANCODE_KBDILLUMUP
  SCANCODE_KBDILLUMUP,

  /// SDL_SCANCODE_EJECT
  SCANCODE_EJECT,

  /// SDL_SCANCODE_SLEEP
  SCANCODE_SLEEP,

  /// SDL_SCANCODE_APP1
  SCANCODE_APP1,

  /// SDL_SCANCODE_APP2
  SCANCODE_APP2,

  /// SDL_SCANCODE_AUDIOREWIND
  SCANCODE_AUDIOREWIND,

  /// SDL_SCANCODE_AUDIOFASTFORWARD
  SCANCODE_AUDIOFASTFORWARD,

  /// SDL_NUM_SCANCODES
  keycode_NUM_SCANCODES,
}

/// Keycodes.
///
/// [SDL Docs](https://wiki.libsdl.org/SDL_Keycode)
enum KeyCode {
  /// SDLK_UNKNOWN
  keycode_UNKNOWN,

  /// SDLK_RETURN
  keycode_RETURN,

  /// SDLK_ESCAPE
  keycode_ESCAPE,

  /// SDLK_BACKSPACE
  keycode_BACKSPACE,

  /// SDLK_TAB
  keycode_TAB,

  /// SDLK_SPACE
  keycode_SPACE,

  /// SDLK_EXCLAIM
  keycode_EXCLAIM,

  /// SDLK_QUOTEDBL
  keycode_QUOTEDBL,

  /// SDLK_HASH
  keycode_HASH,

  /// SDLK_PERCENT
  keycode_PERCENT,

  /// SDLK_DOLLAR
  keycode_DOLLAR,

  /// SDLK_AMPERSAND
  keycode_AMPERSAND,

  /// SDLK_QUOTE
  keycode_QUOTE,

  /// SDLK_LEFTPAREN
  keycode_LEFTPAREN,

  /// SDLK_RIGHTPAREN
  keycode_RIGHTPAREN,

  /// SDLK_ASTERISK
  keycode_ASTERISK,

  /// SDLK_PLUS
  keycode_PLUS,

  /// SDLK_COMMA
  keycode_COMMA,

  /// SDLK_MINUS
  keycode_MINUS,

  /// SDLK_PERIOD
  keycode_PERIOD,

  /// SDLK_SLASH
  keycode_SLASH,

  /// SDLK_0
  keycode_0,

  /// SDLK_1
  keycode_1,

  /// SDLK_2
  keycode_2,

  /// SDLK_3
  keycode_3,

  /// SDLK_4
  keycode_4,

  /// SDLK_5
  keycode_5,

  /// SDLK_6
  keycode_6,

  /// SDLK_7
  keycode_7,

  /// SDLK_8
  keycode_8,

  /// SDLK_9
  keycode_9,

  /// SDLK_COLON
  keycode_COLON,

  /// SDLK_SEMICOLON
  keycode_SEMICOLON,

  /// SDLK_LESS
  keycode_LESS,

  /// SDLK_EQUALS
  keycode_EQUALS,

  /// SDLK_GREATER
  keycode_GREATER,

  /// SDLK_QUESTION
  keycode_QUESTION,

  /// SDLK_AT
  keycode_AT,

  /// SDLK_LEFTBRACKET
  keycode_LEFTBRACKET,

  /// SDLK_BACKSLASH
  keycode_BACKSLASH,

  /// SDLK_RIGHTBRACKET
  keycode_RIGHTBRACKET,

  /// SDLK_CARET
  keycode_CARET,

  /// SDLK_UNDERSCORE
  keycode_UNDERSCORE,

  /// SDLK_BACKQUOTE
  keycode_BACKQUOTE,

  /// SDLK_a
  keycode_a,

  /// SDLK_b
  keycode_b,

  /// SDLK_c
  keycode_c,

  /// SDLK_d
  keycode_d,

  /// SDLK_e
  keycode_e,

  /// SDLK_f
  keycode_f,

  /// SDLK_g
  keycode_g,

  /// SDLK_h
  keycode_h,

  /// SDLK_i
  keycode_i,

  /// SDLK_j
  keycode_j,

  /// SDLK_k
  keycode_k,

  /// SDLK_l
  keycode_l,

  /// SDLK_m
  keycode_m,

  /// SDLK_n
  keycode_n,

  /// SDLK_o
  keycode_o,

  /// SDLK_p
  keycode_p,

  /// SDLK_q
  keycode_q,

  /// SDLK_r
  keycode_r,

  /// SDLK_s
  keycode_s,

  /// SDLK_t
  keycode_t,

  /// SDLK_u
  keycode_u,

  /// SDLK_v
  keycode_v,

  /// SDLK_w
  keycode_w,

  /// SDLK_x
  keycode_x,

  /// SDLK_y
  keycode_y,

  /// SDLK_z
  keycode_z,

  /// SDLK_CAPSLOCK
  keycode_CAPSLOCK,

  /// SDLK_F1
  keycode_F1,

  /// SDLK_F2
  keycode_F2,

  /// SDLK_F3
  keycode_F3,

  /// SDLK_F4
  keycode_F4,

  /// SDLK_F5
  keycode_F5,

  /// SDLK_F6
  keycode_F6,

  /// SDLK_F7
  keycode_F7,

  /// SDLK_F8
  keycode_F8,

  /// SDLK_F9
  keycode_F9,

  /// SDLK_F10
  keycode_F10,

  /// SDLK_F11
  keycode_F11,

  /// SDLK_F12
  keycode_F12,

  /// SDLK_PRINTSCREEN
  keycode_PRINTSCREEN,

  /// SDLK_SCROLLLOCK
  keycode_SCROLLLOCK,

  /// SDLK_PAUSE
  keycode_PAUSE,

  /// SDLK_INSERT
  keycode_INSERT,

  /// SDLK_HOME
  keycode_HOME,

  /// SDLK_PAGEUP
  keycode_PAGEUP,

  /// SDLK_DELETE
  keycode_DELETE,

  /// SDLK_END
  keycode_END,

  /// SDLK_PAGEDOWN
  keycode_PAGEDOWN,

  /// SDLK_RIGHT
  keycode_RIGHT,

  /// SDLK_LEFT
  keycode_LEFT,

  /// SDLK_DOWN
  keycode_DOWN,

  /// SDLK_UP
  keycode_UP,

  /// SDLK_NUMLOCKCLEAR
  keycode_NUMLOCKCLEAR,

  /// SDLK_KP_DIVIDE
  keycode_KP_DIVIDE,

  /// SDLK_KP_MULTIPLY
  keycode_KP_MULTIPLY,

  /// SDLK_KP_MINUS
  keycode_KP_MINUS,

  /// SDLK_KP_PLUS
  keycode_KP_PLUS,

  /// SDLK_KP_ENTER
  keycode_KP_ENTER,

  /// SDLK_KP_1
  keycode_KP_1,

  /// SDLK_KP_2
  keycode_KP_2,

  /// SDLK_KP_3
  keycode_KP_3,

  /// SDLK_KP_4
  keycode_KP_4,

  /// SDLK_KP_5
  keycode_KP_5,

  /// SDLK_KP_6
  keycode_KP_6,

  /// SDLK_KP_7
  keycode_KP_7,

  /// SDLK_KP_8
  keycode_KP_8,

  /// SDLK_KP_9
  keycode_KP_9,

  /// SDLK_KP_0
  keycode_KP_0,

  /// SDLK_KP_PERIOD
  keycode_KP_PERIOD,

  /// SDLK_APPLICATION
  keycode_APPLICATION,

  /// SDLK_POWER
  keycode_POWER,

  /// SDLK_KP_EQUALS
  keycode_KP_EQUALS,

  /// SDLK_F13
  keycode_F13,

  /// SDLK_F14
  keycode_F14,

  /// SDLK_F15
  keycode_F15,

  /// SDLK_F16
  keycode_F16,

  /// SDLK_F17
  keycode_F17,

  /// SDLK_F18
  keycode_F18,

  /// SDLK_F19
  keycode_F19,

  /// SDLK_F20
  keycode_F20,

  /// SDLK_F21
  keycode_F21,

  /// SDLK_F22
  keycode_F22,

  /// SDLK_F23
  keycode_F23,

  /// SDLK_F24
  keycode_F24,

  /// SDLK_EXECUTE
  keycode_EXECUTE,

  /// SDLK_HELP
  keycode_HELP,

  /// SDLK_MENU
  keycode_MENU,

  /// SDLK_SELECT
  keycode_SELECT,

  /// SDLK_STOP
  keycode_STOP,

  /// SDLK_AGAIN
  keycode_AGAIN,

  /// SDLK_UNDO
  keycode_UNDO,

  /// SDLK_CUT
  keycode_CUT,

  /// SDLK_COPY
  keycode_COPY,

  /// SDLK_PASTE
  keycode_PASTE,

  /// SDLK_FIND
  keycode_FIND,

  /// SDLK_MUTE
  keycode_MUTE,

  /// SDLK_VOLUMEUP
  keycode_VOLUMEUP,

  /// SDLK_VOLUMEDOWN
  keycode_VOLUMEDOWN,

  /// SDLK_KP_COMMA
  keycode_KP_COMMA,

  /// SDLK_KP_EQUALSAS400
  keycode_KP_EQUALSAS400,

  /// SDLK_ALTERASE
  keycode_ALTERASE,

  /// SDLK_SYSREQ
  keycode_SYSREQ,

  /// SDLK_CANCEL
  keycode_CANCEL,

  /// SDLK_CLEAR
  keycode_CLEAR,

  /// SDLK_PRIOR
  keycode_PRIOR,

  /// SDLK_RETURN2
  keycode_RETURN2,

  /// SDLK_SEPARATOR
  keycode_SEPARATOR,

  /// SDLK_OUT
  keycode_OUT,

  /// SDLK_OPER
  keycode_OPER,

  /// SDLK_CLEARAGAIN
  keycode_CLEARAGAIN,

  /// SDLK_CRSEL
  keycode_CRSEL,

  /// SDLK_EXSEL
  keycode_EXSEL,

  /// SDLK_KP_00
  keycode_KP_00,

  /// SDLK_KP_000
  keycode_KP_000,

  /// SDLK_THOUSANDSSEPARATOR
  keycode_THOUSANDSSEPARATOR,

  /// SDLK_DECIMALSEPARATOR
  keycode_DECIMALSEPARATOR,

  /// SDLK_CURRENCYUNIT
  keycode_CURRENCYUNIT,

  /// SDLK_CURRENCYSUBUNIT
  keycode_CURRENCYSUBUNIT,

  /// SDLK_KP_LEFTPAREN
  keycode_KP_LEFTPAREN,

  /// SDLK_KP_RIGHTPAREN
  keycode_KP_RIGHTPAREN,

  /// SDLK_KP_LEFTBRACE
  keycode_KP_LEFTBRACE,

  /// SDLK_KP_RIGHTBRACE
  keycode_KP_RIGHTBRACE,

  /// SDLK_KP_TAB
  keycode_KP_TAB,

  /// SDLK_KP_BACKSPACE
  keycode_KP_BACKSPACE,

  /// SDLK_KP_A
  keycode_KP_A,

  /// SDLK_KP_B
  keycode_KP_B,

  /// SDLK_KP_C
  keycode_KP_C,

  /// SDLK_KP_D
  keycode_KP_D,

  /// SDLK_KP_E
  keycode_KP_E,

  /// SDLK_KP_F
  keycode_KP_F,

  /// SDLK_KP_XOR
  keycode_KP_XOR,

  /// SDLK_KP_POWER
  keycode_KP_POWER,

  /// SDLK_KP_PERCENT
  keycode_KP_PERCENT,

  /// SDLK_KP_LESS
  keycode_KP_LESS,

  /// SDLK_KP_GREATER
  keycode_KP_GREATER,

  /// SDLK_KP_AMPERSAND
  keycode_KP_AMPERSAND,

  /// SDLK_KP_DBLAMPERSAND
  keycode_KP_DBLAMPERSAND,

  /// SDLK_KP_VERTICALBAR
  keycode_KP_VERTICALBAR,

  /// SDLK_KP_DBLVERTICALBAR
  keycode_KP_DBLVERTICALBAR,

  /// SDLK_KP_COLON
  keycode_KP_COLON,

  /// SDLK_KP_HASH
  keycode_KP_HASH,

  /// SDLK_KP_SPACE
  keycode_KP_SPACE,

  /// SDLK_KP_AT
  keycode_KP_AT,

  /// SDLK_KP_EXCLAM
  keycode_KP_EXCLAM,

  /// SDLK_KP_MEMSTORE
  keycode_KP_MEMSTORE,

  /// SDLK_KP_MEMRECALL
  keycode_KP_MEMRECALL,

  /// SDLK_KP_MEMCLEAR
  keycode_KP_MEMCLEAR,

  /// SDLK_KP_MEMADD
  keycode_KP_MEMADD,

  /// SDLK_KP_MEMSUBTRACT
  keycode_KP_MEMSUBTRACT,

  /// SDLK_KP_MEMMULTIPLY
  keycode_KP_MEMMULTIPLY,

  /// SDLK_KP_MEMDIVIDE
  keycode_KP_MEMDIVIDE,

  /// SDLK_KP_PLUSMINUS
  keycode_KP_PLUSMINUS,

  /// SDLK_KP_CLEAR
  keycode_KP_CLEAR,

  /// SDLK_KP_CLEARENTRY
  keycode_KP_CLEARENTRY,

  /// SDLK_KP_BINARY
  keycode_KP_BINARY,

  /// SDLK_KP_OCTAL
  keycode_KP_OCTAL,

  /// SDLK_KP_DECIMAL
  keycode_KP_DECIMAL,

  /// SDLK_KP_HEXADECIMAL
  keycode_KP_HEXADECIMAL,

  /// SDLK_LCTRL
  keycode_LCTRL,

  /// SDLK_LSHIFT
  keycode_LSHIFT,

  /// SDLK_LALT
  keycode_LALT,

  /// SDLK_LGUI
  keycode_LGUI,

  /// SDLK_RCTRL
  keycode_RCTRL,

  /// SDLK_RSHIFT
  keycode_RSHIFT,

  /// SDLK_RALT
  keycode_RALT,

  /// SDLK_RGUI
  keycode_RGUI,

  /// SDLK_MODE
  keycode_MODE,

  /// SDLK_AUDIONEXT
  keycode_AUDIONEXT,

  /// SDLK_AUDIOPREV
  keycode_AUDIOPREV,

  /// SDLK_AUDIOSTOP
  keycode_AUDIOSTOP,

  /// SDLK_AUDIOPLAY
  keycode_AUDIOPLAY,

  /// SDLK_AUDIOMUTE
  keycode_AUDIOMUTE,

  /// SDLK_MEDIASELECT
  keycode_MEDIASELECT,

  /// SDLK_WWW
  keycode_WWW,

  /// SDLK_MAIL
  keycode_MAIL,

  /// SDLK_CALCULATOR
  keycode_CALCULATOR,

  /// SDLK_COMPUTER
  keycode_COMPUTER,

  /// SDLK_AC_SEARCH
  keycode_AC_SEARCH,

  /// SDLK_AC_HOME
  keycode_AC_HOME,

  /// SDLK_AC_BACK
  keycode_AC_BACK,

  /// SDLK_AC_FORWARD
  keycode_AC_FORWARD,

  /// SDLK_AC_STOP
  keycode_AC_STOP,

  /// SDLK_AC_REFRESH
  keycode_AC_REFRESH,

  /// SDLK_AC_BOOKMARKS
  keycode_AC_BOOKMARKS,

  /// SDLK_BRIGHTNESSDOWN
  keycode_BRIGHTNESSDOWN,

  /// SDLK_BRIGHTNESSUP
  keycode_BRIGHTNESSUP,

  /// SDLK_DISPLAYSWITCH
  keycode_DISPLAYSWITCH,

  /// SDLK_KBDILLUMTOGGLE
  keycode_KBDILLUMTOGGLE,

  /// SDLK_KBDILLUMDOWN
  keycode_KBDILLUMDOWN,

  /// SDLK_KBDILLUMUP
  keycode_KBDILLUMUP,

  /// SDLK_EJECT
  keycode_EJECT,

  /// SDLK_SLEEP
  keycode_SLEEP,

  /// SDLK_APP1
  keycode_APP1,

  /// SDLK_APP2
  keycode_APP2,

  /// SDLK_AUDIOREWIND
  keycode_AUDIOREWIND,

  /// SDLK_AUDIOFASTFORWARD
  keycode_AUDIOFASTFORWARD,
}

/// An extension to return a [ScanCode] from an integer.
extension DartSdlScanCodeMethods on int {
  /// Return a scancode value.
  ScanCode toScanCode() {
    switch (this) {
      case SDL_Scancode.SDL_SCANCODE_UNKNOWN:
        return ScanCode.SCANCODE_UNKNOWN;
      case SDL_Scancode.SDL_SCANCODE_A:
        return ScanCode.SCANCODE_A;
      case SDL_Scancode.SDL_SCANCODE_B:
        return ScanCode.SCANCODE_B;
      case SDL_Scancode.SDL_SCANCODE_C:
        return ScanCode.SCANCODE_C;
      case SDL_Scancode.SDL_SCANCODE_D:
        return ScanCode.SCANCODE_D;
      case SDL_Scancode.SDL_SCANCODE_E:
        return ScanCode.SCANCODE_E;
      case SDL_Scancode.SDL_SCANCODE_F:
        return ScanCode.SCANCODE_F;
      case SDL_Scancode.SDL_SCANCODE_G:
        return ScanCode.SCANCODE_G;
      case SDL_Scancode.SDL_SCANCODE_H:
        return ScanCode.SCANCODE_H;
      case SDL_Scancode.SDL_SCANCODE_I:
        return ScanCode.SCANCODE_I;
      case SDL_Scancode.SDL_SCANCODE_J:
        return ScanCode.SCANCODE_J;
      case SDL_Scancode.SDL_SCANCODE_K:
        return ScanCode.SCANCODE_K;
      case SDL_Scancode.SDL_SCANCODE_L:
        return ScanCode.SCANCODE_L;
      case SDL_Scancode.SDL_SCANCODE_M:
        return ScanCode.SCANCODE_M;
      case SDL_Scancode.SDL_SCANCODE_N:
        return ScanCode.SCANCODE_N;
      case SDL_Scancode.SDL_SCANCODE_O:
        return ScanCode.SCANCODE_O;
      case SDL_Scancode.SDL_SCANCODE_P:
        return ScanCode.SCANCODE_P;
      case SDL_Scancode.SDL_SCANCODE_Q:
        return ScanCode.SCANCODE_Q;
      case SDL_Scancode.SDL_SCANCODE_R:
        return ScanCode.SCANCODE_R;
      case SDL_Scancode.SDL_SCANCODE_S:
        return ScanCode.SCANCODE_S;
      case SDL_Scancode.SDL_SCANCODE_T:
        return ScanCode.SCANCODE_T;
      case SDL_Scancode.SDL_SCANCODE_U:
        return ScanCode.SCANCODE_U;
      case SDL_Scancode.SDL_SCANCODE_V:
        return ScanCode.SCANCODE_V;
      case SDL_Scancode.SDL_SCANCODE_W:
        return ScanCode.SCANCODE_W;
      case SDL_Scancode.SDL_SCANCODE_X:
        return ScanCode.SCANCODE_X;
      case SDL_Scancode.SDL_SCANCODE_Y:
        return ScanCode.SCANCODE_Y;
      case SDL_Scancode.SDL_SCANCODE_Z:
        return ScanCode.SCANCODE_Z;
      case SDL_Scancode.SDL_SCANCODE_1:
        return ScanCode.SCANCODE_1;
      case SDL_Scancode.SDL_SCANCODE_2:
        return ScanCode.SCANCODE_2;
      case SDL_Scancode.SDL_SCANCODE_3:
        return ScanCode.SCANCODE_3;
      case SDL_Scancode.SDL_SCANCODE_4:
        return ScanCode.SCANCODE_4;
      case SDL_Scancode.SDL_SCANCODE_5:
        return ScanCode.SCANCODE_5;
      case SDL_Scancode.SDL_SCANCODE_6:
        return ScanCode.SCANCODE_6;
      case SDL_Scancode.SDL_SCANCODE_7:
        return ScanCode.SCANCODE_7;
      case SDL_Scancode.SDL_SCANCODE_8:
        return ScanCode.SCANCODE_8;
      case SDL_Scancode.SDL_SCANCODE_9:
        return ScanCode.SCANCODE_9;
      case SDL_Scancode.SDL_SCANCODE_0:
        return ScanCode.SCANCODE_0;
      case SDL_Scancode.SDL_SCANCODE_RETURN:
        return ScanCode.SCANCODE_RETURN;
      case SDL_Scancode.SDL_SCANCODE_ESCAPE:
        return ScanCode.SCANCODE_ESCAPE;
      case SDL_Scancode.SDL_SCANCODE_BACKSPACE:
        return ScanCode.SCANCODE_BACKSPACE;
      case SDL_Scancode.SDL_SCANCODE_TAB:
        return ScanCode.SCANCODE_TAB;
      case SDL_Scancode.SDL_SCANCODE_SPACE:
        return ScanCode.SCANCODE_SPACE;
      case SDL_Scancode.SDL_SCANCODE_MINUS:
        return ScanCode.SCANCODE_MINUS;
      case SDL_Scancode.SDL_SCANCODE_EQUALS:
        return ScanCode.SCANCODE_EQUALS;
      case SDL_Scancode.SDL_SCANCODE_LEFTBRACKET:
        return ScanCode.SCANCODE_LEFTBRACKET;
      case SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET:
        return ScanCode.SCANCODE_RIGHTBRACKET;
      case SDL_Scancode.SDL_SCANCODE_BACKSLASH:
        return ScanCode.SCANCODE_BACKSLASH;
      case SDL_Scancode.SDL_SCANCODE_NONUSHASH:
        return ScanCode.SCANCODE_NONUSHASH;
      case SDL_Scancode.SDL_SCANCODE_SEMICOLON:
        return ScanCode.SCANCODE_SEMICOLON;
      case SDL_Scancode.SDL_SCANCODE_APOSTROPHE:
        return ScanCode.SCANCODE_APOSTROPHE;
      case SDL_Scancode.SDL_SCANCODE_GRAVE:
        return ScanCode.SCANCODE_GRAVE;
      case SDL_Scancode.SDL_SCANCODE_COMMA:
        return ScanCode.SCANCODE_COMMA;
      case SDL_Scancode.SDL_SCANCODE_PERIOD:
        return ScanCode.SCANCODE_PERIOD;
      case SDL_Scancode.SDL_SCANCODE_SLASH:
        return ScanCode.SCANCODE_SLASH;
      case SDL_Scancode.SDL_SCANCODE_CAPSLOCK:
        return ScanCode.SCANCODE_CAPSLOCK;
      case SDL_Scancode.SDL_SCANCODE_F1:
        return ScanCode.SCANCODE_F1;
      case SDL_Scancode.SDL_SCANCODE_F2:
        return ScanCode.SCANCODE_F2;
      case SDL_Scancode.SDL_SCANCODE_F3:
        return ScanCode.SCANCODE_F3;
      case SDL_Scancode.SDL_SCANCODE_F4:
        return ScanCode.SCANCODE_F4;
      case SDL_Scancode.SDL_SCANCODE_F5:
        return ScanCode.SCANCODE_F5;
      case SDL_Scancode.SDL_SCANCODE_F6:
        return ScanCode.SCANCODE_F6;
      case SDL_Scancode.SDL_SCANCODE_F7:
        return ScanCode.SCANCODE_F7;
      case SDL_Scancode.SDL_SCANCODE_F8:
        return ScanCode.SCANCODE_F8;
      case SDL_Scancode.SDL_SCANCODE_F9:
        return ScanCode.SCANCODE_F9;
      case SDL_Scancode.SDL_SCANCODE_F10:
        return ScanCode.SCANCODE_F10;
      case SDL_Scancode.SDL_SCANCODE_F11:
        return ScanCode.SCANCODE_F11;
      case SDL_Scancode.SDL_SCANCODE_F12:
        return ScanCode.SCANCODE_F12;
      case SDL_Scancode.SDL_SCANCODE_PRINTSCREEN:
        return ScanCode.SCANCODE_PRINTSCREEN;
      case SDL_Scancode.SDL_SCANCODE_SCROLLLOCK:
        return ScanCode.SCANCODE_SCROLLLOCK;
      case SDL_Scancode.SDL_SCANCODE_PAUSE:
        return ScanCode.SCANCODE_PAUSE;
      case SDL_Scancode.SDL_SCANCODE_INSERT:
        return ScanCode.SCANCODE_INSERT;
      case SDL_Scancode.SDL_SCANCODE_HOME:
        return ScanCode.SCANCODE_HOME;
      case SDL_Scancode.SDL_SCANCODE_PAGEUP:
        return ScanCode.SCANCODE_PAGEUP;
      case SDL_Scancode.SDL_SCANCODE_DELETE:
        return ScanCode.SCANCODE_DELETE;
      case SDL_Scancode.SDL_SCANCODE_END:
        return ScanCode.SCANCODE_END;
      case SDL_Scancode.SDL_SCANCODE_PAGEDOWN:
        return ScanCode.SCANCODE_PAGEDOWN;
      case SDL_Scancode.SDL_SCANCODE_RIGHT:
        return ScanCode.SCANCODE_RIGHT;
      case SDL_Scancode.SDL_SCANCODE_LEFT:
        return ScanCode.SCANCODE_LEFT;
      case SDL_Scancode.SDL_SCANCODE_DOWN:
        return ScanCode.SCANCODE_DOWN;
      case SDL_Scancode.SDL_SCANCODE_UP:
        return ScanCode.SCANCODE_UP;
      case SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR:
        return ScanCode.SCANCODE_NUMLOCKCLEAR;
      case SDL_Scancode.SDL_SCANCODE_KP_DIVIDE:
        return ScanCode.SCANCODE_KP_DIVIDE;
      case SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY:
        return ScanCode.SCANCODE_KP_MULTIPLY;
      case SDL_Scancode.SDL_SCANCODE_KP_MINUS:
        return ScanCode.SCANCODE_KP_MINUS;
      case SDL_Scancode.SDL_SCANCODE_KP_PLUS:
        return ScanCode.SCANCODE_KP_PLUS;
      case SDL_Scancode.SDL_SCANCODE_KP_ENTER:
        return ScanCode.SCANCODE_KP_ENTER;
      case SDL_Scancode.SDL_SCANCODE_KP_1:
        return ScanCode.SCANCODE_KP_1;
      case SDL_Scancode.SDL_SCANCODE_KP_2:
        return ScanCode.SCANCODE_KP_2;
      case SDL_Scancode.SDL_SCANCODE_KP_3:
        return ScanCode.SCANCODE_KP_3;
      case SDL_Scancode.SDL_SCANCODE_KP_4:
        return ScanCode.SCANCODE_KP_4;
      case SDL_Scancode.SDL_SCANCODE_KP_5:
        return ScanCode.SCANCODE_KP_5;
      case SDL_Scancode.SDL_SCANCODE_KP_6:
        return ScanCode.SCANCODE_KP_6;
      case SDL_Scancode.SDL_SCANCODE_KP_7:
        return ScanCode.SCANCODE_KP_7;
      case SDL_Scancode.SDL_SCANCODE_KP_8:
        return ScanCode.SCANCODE_KP_8;
      case SDL_Scancode.SDL_SCANCODE_KP_9:
        return ScanCode.SCANCODE_KP_9;
      case SDL_Scancode.SDL_SCANCODE_KP_0:
        return ScanCode.SCANCODE_KP_0;
      case SDL_Scancode.SDL_SCANCODE_KP_PERIOD:
        return ScanCode.SCANCODE_KP_PERIOD;
      case SDL_Scancode.SDL_SCANCODE_NONUSBACKSLASH:
        return ScanCode.SCANCODE_NONUSBACKSLASH;
      case SDL_Scancode.SDL_SCANCODE_APPLICATION:
        return ScanCode.SCANCODE_APPLICATION;
      case SDL_Scancode.SDL_SCANCODE_POWER:
        return ScanCode.SCANCODE_POWER;
      case SDL_Scancode.SDL_SCANCODE_KP_EQUALS:
        return ScanCode.SCANCODE_KP_EQUALS;
      case SDL_Scancode.SDL_SCANCODE_F13:
        return ScanCode.SCANCODE_F13;
      case SDL_Scancode.SDL_SCANCODE_F14:
        return ScanCode.SCANCODE_F14;
      case SDL_Scancode.SDL_SCANCODE_F15:
        return ScanCode.SCANCODE_F15;
      case SDL_Scancode.SDL_SCANCODE_F16:
        return ScanCode.SCANCODE_F16;
      case SDL_Scancode.SDL_SCANCODE_F17:
        return ScanCode.SCANCODE_F17;
      case SDL_Scancode.SDL_SCANCODE_F18:
        return ScanCode.SCANCODE_F18;
      case SDL_Scancode.SDL_SCANCODE_F19:
        return ScanCode.SCANCODE_F19;
      case SDL_Scancode.SDL_SCANCODE_F20:
        return ScanCode.SCANCODE_F20;
      case SDL_Scancode.SDL_SCANCODE_F21:
        return ScanCode.SCANCODE_F21;
      case SDL_Scancode.SDL_SCANCODE_F22:
        return ScanCode.SCANCODE_F22;
      case SDL_Scancode.SDL_SCANCODE_F23:
        return ScanCode.SCANCODE_F23;
      case SDL_Scancode.SDL_SCANCODE_F24:
        return ScanCode.SCANCODE_F24;
      case SDL_Scancode.SDL_SCANCODE_EXECUTE:
        return ScanCode.SCANCODE_EXECUTE;
      case SDL_Scancode.SDL_SCANCODE_HELP:
        return ScanCode.SCANCODE_HELP;
      case SDL_Scancode.SDL_SCANCODE_MENU:
        return ScanCode.SCANCODE_MENU;
      case SDL_Scancode.SDL_SCANCODE_SELECT:
        return ScanCode.SCANCODE_SELECT;
      case SDL_Scancode.SDL_SCANCODE_STOP:
        return ScanCode.SCANCODE_STOP;
      case SDL_Scancode.SDL_SCANCODE_AGAIN:
        return ScanCode.SCANCODE_AGAIN;
      case SDL_Scancode.SDL_SCANCODE_UNDO:
        return ScanCode.SCANCODE_UNDO;
      case SDL_Scancode.SDL_SCANCODE_CUT:
        return ScanCode.SCANCODE_CUT;
      case SDL_Scancode.SDL_SCANCODE_COPY:
        return ScanCode.SCANCODE_COPY;
      case SDL_Scancode.SDL_SCANCODE_PASTE:
        return ScanCode.SCANCODE_PASTE;
      case SDL_Scancode.SDL_SCANCODE_FIND:
        return ScanCode.SCANCODE_FIND;
      case SDL_Scancode.SDL_SCANCODE_MUTE:
        return ScanCode.SCANCODE_MUTE;
      case SDL_Scancode.SDL_SCANCODE_VOLUMEUP:
        return ScanCode.SCANCODE_VOLUMEUP;
      case SDL_Scancode.SDL_SCANCODE_VOLUMEDOWN:
        return ScanCode.SCANCODE_VOLUMEDOWN;
      case SDL_Scancode.SDL_SCANCODE_KP_COMMA:
        return ScanCode.SCANCODE_KP_COMMA;
      case SDL_Scancode.SDL_SCANCODE_KP_EQUALSAS400:
        return ScanCode.SCANCODE_KP_EQUALSAS400;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL1:
        return ScanCode.SCANCODE_INTERNATIONAL1;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL2:
        return ScanCode.SCANCODE_INTERNATIONAL2;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL3:
        return ScanCode.SCANCODE_INTERNATIONAL3;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL4:
        return ScanCode.SCANCODE_INTERNATIONAL4;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL5:
        return ScanCode.SCANCODE_INTERNATIONAL5;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL6:
        return ScanCode.SCANCODE_INTERNATIONAL6;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL7:
        return ScanCode.SCANCODE_INTERNATIONAL7;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL8:
        return ScanCode.SCANCODE_INTERNATIONAL8;
      case SDL_Scancode.SDL_SCANCODE_INTERNATIONAL9:
        return ScanCode.SCANCODE_INTERNATIONAL9;
      case SDL_Scancode.SDL_SCANCODE_LANG1:
        return ScanCode.SCANCODE_LANG1;
      case SDL_Scancode.SDL_SCANCODE_LANG2:
        return ScanCode.SCANCODE_LANG2;
      case SDL_Scancode.SDL_SCANCODE_LANG3:
        return ScanCode.SCANCODE_LANG3;
      case SDL_Scancode.SDL_SCANCODE_LANG4:
        return ScanCode.SCANCODE_LANG4;
      case SDL_Scancode.SDL_SCANCODE_LANG5:
        return ScanCode.SCANCODE_LANG5;
      case SDL_Scancode.SDL_SCANCODE_LANG6:
        return ScanCode.SCANCODE_LANG6;
      case SDL_Scancode.SDL_SCANCODE_LANG7:
        return ScanCode.SCANCODE_LANG7;
      case SDL_Scancode.SDL_SCANCODE_LANG8:
        return ScanCode.SCANCODE_LANG8;
      case SDL_Scancode.SDL_SCANCODE_LANG9:
        return ScanCode.SCANCODE_LANG9;
      case SDL_Scancode.SDL_SCANCODE_ALTERASE:
        return ScanCode.SCANCODE_ALTERASE;
      case SDL_Scancode.SDL_SCANCODE_SYSREQ:
        return ScanCode.SCANCODE_SYSREQ;
      case SDL_Scancode.SDL_SCANCODE_CANCEL:
        return ScanCode.SCANCODE_CANCEL;
      case SDL_Scancode.SDL_SCANCODE_CLEAR:
        return ScanCode.SCANCODE_CLEAR;
      case SDL_Scancode.SDL_SCANCODE_PRIOR:
        return ScanCode.SCANCODE_PRIOR;
      case SDL_Scancode.SDL_SCANCODE_RETURN2:
        return ScanCode.SCANCODE_RETURN2;
      case SDL_Scancode.SDL_SCANCODE_SEPARATOR:
        return ScanCode.SCANCODE_SEPARATOR;
      case SDL_Scancode.SDL_SCANCODE_OUT:
        return ScanCode.SCANCODE_OUT;
      case SDL_Scancode.SDL_SCANCODE_OPER:
        return ScanCode.SCANCODE_OPER;
      case SDL_Scancode.SDL_SCANCODE_CLEARAGAIN:
        return ScanCode.SCANCODE_CLEARAGAIN;
      case SDL_Scancode.SDL_SCANCODE_CRSEL:
        return ScanCode.SCANCODE_CRSEL;
      case SDL_Scancode.SDL_SCANCODE_EXSEL:
        return ScanCode.SCANCODE_EXSEL;
      case SDL_Scancode.SDL_SCANCODE_KP_00:
        return ScanCode.SCANCODE_KP_00;
      case SDL_Scancode.SDL_SCANCODE_KP_000:
        return ScanCode.SCANCODE_KP_000;
      case SDL_Scancode.SDL_SCANCODE_THOUSANDSSEPARATOR:
        return ScanCode.SCANCODE_THOUSANDSSEPARATOR;
      case SDL_Scancode.SDL_SCANCODE_DECIMALSEPARATOR:
        return ScanCode.SCANCODE_DECIMALSEPARATOR;
      case SDL_Scancode.SDL_SCANCODE_CURRENCYUNIT:
        return ScanCode.SCANCODE_CURRENCYUNIT;
      case SDL_Scancode.SDL_SCANCODE_CURRENCYSUBUNIT:
        return ScanCode.SCANCODE_CURRENCYSUBUNIT;
      case SDL_Scancode.SDL_SCANCODE_KP_LEFTPAREN:
        return ScanCode.SCANCODE_KP_LEFTPAREN;
      case SDL_Scancode.SDL_SCANCODE_KP_RIGHTPAREN:
        return ScanCode.SCANCODE_KP_RIGHTPAREN;
      case SDL_Scancode.SDL_SCANCODE_KP_LEFTBRACE:
        return ScanCode.SCANCODE_KP_LEFTBRACE;
      case SDL_Scancode.SDL_SCANCODE_KP_RIGHTBRACE:
        return ScanCode.SCANCODE_KP_RIGHTBRACE;
      case SDL_Scancode.SDL_SCANCODE_KP_TAB:
        return ScanCode.SCANCODE_KP_TAB;
      case SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE:
        return ScanCode.SCANCODE_KP_BACKSPACE;
      case SDL_Scancode.SDL_SCANCODE_KP_A:
        return ScanCode.SCANCODE_KP_A;
      case SDL_Scancode.SDL_SCANCODE_KP_B:
        return ScanCode.SCANCODE_KP_B;
      case SDL_Scancode.SDL_SCANCODE_KP_C:
        return ScanCode.SCANCODE_KP_C;
      case SDL_Scancode.SDL_SCANCODE_KP_D:
        return ScanCode.SCANCODE_KP_D;
      case SDL_Scancode.SDL_SCANCODE_KP_E:
        return ScanCode.SCANCODE_KP_E;
      case SDL_Scancode.SDL_SCANCODE_KP_F:
        return ScanCode.SCANCODE_KP_F;
      case SDL_Scancode.SDL_SCANCODE_KP_XOR:
        return ScanCode.SCANCODE_KP_XOR;
      case SDL_Scancode.SDL_SCANCODE_KP_POWER:
        return ScanCode.SCANCODE_KP_POWER;
      case SDL_Scancode.SDL_SCANCODE_KP_PERCENT:
        return ScanCode.SCANCODE_KP_PERCENT;
      case SDL_Scancode.SDL_SCANCODE_KP_LESS:
        return ScanCode.SCANCODE_KP_LESS;
      case SDL_Scancode.SDL_SCANCODE_KP_GREATER:
        return ScanCode.SCANCODE_KP_GREATER;
      case SDL_Scancode.SDL_SCANCODE_KP_AMPERSAND:
        return ScanCode.SCANCODE_KP_AMPERSAND;
      case SDL_Scancode.SDL_SCANCODE_KP_DBLAMPERSAND:
        return ScanCode.SCANCODE_KP_DBLAMPERSAND;
      case SDL_Scancode.SDL_SCANCODE_KP_VERTICALBAR:
        return ScanCode.SCANCODE_KP_VERTICALBAR;
      case SDL_Scancode.SDL_SCANCODE_KP_DBLVERTICALBAR:
        return ScanCode.SCANCODE_KP_DBLVERTICALBAR;
      case SDL_Scancode.SDL_SCANCODE_KP_COLON:
        return ScanCode.SCANCODE_KP_COLON;
      case SDL_Scancode.SDL_SCANCODE_KP_HASH:
        return ScanCode.SCANCODE_KP_HASH;
      case SDL_Scancode.SDL_SCANCODE_KP_SPACE:
        return ScanCode.SCANCODE_KP_SPACE;
      case SDL_Scancode.SDL_SCANCODE_KP_AT:
        return ScanCode.SCANCODE_KP_AT;
      case SDL_Scancode.SDL_SCANCODE_KP_EXCLAM:
        return ScanCode.SCANCODE_KP_EXCLAM;
      case SDL_Scancode.SDL_SCANCODE_KP_MEMSTORE:
        return ScanCode.SCANCODE_KP_MEMSTORE;
      case SDL_Scancode.SDL_SCANCODE_KP_MEMRECALL:
        return ScanCode.SCANCODE_KP_MEMRECALL;
      case SDL_Scancode.SDL_SCANCODE_KP_MEMCLEAR:
        return ScanCode.SCANCODE_KP_MEMCLEAR;
      case SDL_Scancode.SDL_SCANCODE_KP_MEMADD:
        return ScanCode.SCANCODE_KP_MEMADD;
      case SDL_Scancode.SDL_SCANCODE_KP_MEMSUBTRACT:
        return ScanCode.SCANCODE_KP_MEMSUBTRACT;
      case SDL_Scancode.SDL_SCANCODE_KP_MEMMULTIPLY:
        return ScanCode.SCANCODE_KP_MEMMULTIPLY;
      case SDL_Scancode.SDL_SCANCODE_KP_MEMDIVIDE:
        return ScanCode.SCANCODE_KP_MEMDIVIDE;
      case SDL_Scancode.SDL_SCANCODE_KP_PLUSMINUS:
        return ScanCode.SCANCODE_KP_PLUSMINUS;
      case SDL_Scancode.SDL_SCANCODE_KP_CLEAR:
        return ScanCode.SCANCODE_KP_CLEAR;
      case SDL_Scancode.SDL_SCANCODE_KP_CLEARENTRY:
        return ScanCode.SCANCODE_KP_CLEARENTRY;
      case SDL_Scancode.SDL_SCANCODE_KP_BINARY:
        return ScanCode.SCANCODE_KP_BINARY;
      case SDL_Scancode.SDL_SCANCODE_KP_OCTAL:
        return ScanCode.SCANCODE_KP_OCTAL;
      case SDL_Scancode.SDL_SCANCODE_KP_DECIMAL:
        return ScanCode.SCANCODE_KP_DECIMAL;
      case SDL_Scancode.SDL_SCANCODE_KP_HEXADECIMAL:
        return ScanCode.SCANCODE_KP_HEXADECIMAL;
      case SDL_Scancode.SDL_SCANCODE_LCTRL:
        return ScanCode.SCANCODE_LCTRL;
      case SDL_Scancode.SDL_SCANCODE_LSHIFT:
        return ScanCode.SCANCODE_LSHIFT;
      case SDL_Scancode.SDL_SCANCODE_LALT:
        return ScanCode.SCANCODE_LALT;
      case SDL_Scancode.SDL_SCANCODE_LGUI:
        return ScanCode.SCANCODE_LGUI;
      case SDL_Scancode.SDL_SCANCODE_RCTRL:
        return ScanCode.SCANCODE_RCTRL;
      case SDL_Scancode.SDL_SCANCODE_RSHIFT:
        return ScanCode.SCANCODE_RSHIFT;
      case SDL_Scancode.SDL_SCANCODE_RALT:
        return ScanCode.SCANCODE_RALT;
      case SDL_Scancode.SDL_SCANCODE_RGUI:
        return ScanCode.SCANCODE_RGUI;
      case SDL_Scancode.SDL_SCANCODE_MODE:
        return ScanCode.SCANCODE_MODE;
      case SDL_Scancode.SDL_SCANCODE_AUDIONEXT:
        return ScanCode.SCANCODE_AUDIONEXT;
      case SDL_Scancode.SDL_SCANCODE_AUDIOPREV:
        return ScanCode.SCANCODE_AUDIOPREV;
      case SDL_Scancode.SDL_SCANCODE_AUDIOSTOP:
        return ScanCode.SCANCODE_AUDIOSTOP;
      case SDL_Scancode.SDL_SCANCODE_AUDIOPLAY:
        return ScanCode.SCANCODE_AUDIOPLAY;
      case SDL_Scancode.SDL_SCANCODE_AUDIOMUTE:
        return ScanCode.SCANCODE_AUDIOMUTE;
      case SDL_Scancode.SDL_SCANCODE_MEDIASELECT:
        return ScanCode.SCANCODE_MEDIASELECT;
      case SDL_Scancode.SDL_SCANCODE_WWW:
        return ScanCode.SCANCODE_WWW;
      case SDL_Scancode.SDL_SCANCODE_MAIL:
        return ScanCode.SCANCODE_MAIL;
      case SDL_Scancode.SDL_SCANCODE_CALCULATOR:
        return ScanCode.SCANCODE_CALCULATOR;
      case SDL_Scancode.SDL_SCANCODE_COMPUTER:
        return ScanCode.SCANCODE_COMPUTER;
      case SDL_Scancode.SDL_SCANCODE_AC_SEARCH:
        return ScanCode.SCANCODE_AC_SEARCH;
      case SDL_Scancode.SDL_SCANCODE_AC_HOME:
        return ScanCode.SCANCODE_AC_HOME;
      case SDL_Scancode.SDL_SCANCODE_AC_BACK:
        return ScanCode.SCANCODE_AC_BACK;
      case SDL_Scancode.SDL_SCANCODE_AC_FORWARD:
        return ScanCode.SCANCODE_AC_FORWARD;
      case SDL_Scancode.SDL_SCANCODE_AC_STOP:
        return ScanCode.SCANCODE_AC_STOP;
      case SDL_Scancode.SDL_SCANCODE_AC_REFRESH:
        return ScanCode.SCANCODE_AC_REFRESH;
      case SDL_Scancode.SDL_SCANCODE_AC_BOOKMARKS:
        return ScanCode.SCANCODE_AC_BOOKMARKS;
      case SDL_Scancode.SDL_SCANCODE_BRIGHTNESSDOWN:
        return ScanCode.SCANCODE_BRIGHTNESSDOWN;
      case SDL_Scancode.SDL_SCANCODE_BRIGHTNESSUP:
        return ScanCode.SCANCODE_BRIGHTNESSUP;
      case SDL_Scancode.SDL_SCANCODE_DISPLAYSWITCH:
        return ScanCode.SCANCODE_DISPLAYSWITCH;
      case SDL_Scancode.SDL_SCANCODE_KBDILLUMTOGGLE:
        return ScanCode.SCANCODE_KBDILLUMTOGGLE;
      case SDL_Scancode.SDL_SCANCODE_KBDILLUMDOWN:
        return ScanCode.SCANCODE_KBDILLUMDOWN;
      case SDL_Scancode.SDL_SCANCODE_KBDILLUMUP:
        return ScanCode.SCANCODE_KBDILLUMUP;
      case SDL_Scancode.SDL_SCANCODE_EJECT:
        return ScanCode.SCANCODE_EJECT;
      case SDL_Scancode.SDL_SCANCODE_SLEEP:
        return ScanCode.SCANCODE_SLEEP;
      case SDL_Scancode.SDL_SCANCODE_APP1:
        return ScanCode.SCANCODE_APP1;
      case SDL_Scancode.SDL_SCANCODE_APP2:
        return ScanCode.SCANCODE_APP2;
      case SDL_Scancode.SDL_SCANCODE_AUDIOREWIND:
        return ScanCode.SCANCODE_AUDIOREWIND;
      case SDL_Scancode.SDL_SCANCODE_AUDIOFASTFORWARD:
        return ScanCode.SCANCODE_AUDIOFASTFORWARD;
      case SDL_Scancode.SDL_NUM_SCANCODES:
        return ScanCode.keycode_NUM_SCANCODES;
      default:
        throw SdlError(this, 'Unknown scancode.');
    }
  }
}

/// An extension to return a [KeyCode] from an integer.
extension DartSdlKeyCodeMethods on int {
  /// Return a keycode value.
  KeyCode toKeyCode() {
    switch (this) {
      case SDL_KeyCode.SDLK_UNKNOWN:
        return KeyCode.keycode_UNKNOWN;
      case SDL_KeyCode.SDLK_RETURN:
        return KeyCode.keycode_RETURN;
      case SDL_KeyCode.SDLK_ESCAPE:
        return KeyCode.keycode_ESCAPE;
      case SDL_KeyCode.SDLK_BACKSPACE:
        return KeyCode.keycode_BACKSPACE;
      case SDL_KeyCode.SDLK_TAB:
        return KeyCode.keycode_TAB;
      case SDL_KeyCode.SDLK_SPACE:
        return KeyCode.keycode_SPACE;
      case SDL_KeyCode.SDLK_EXCLAIM:
        return KeyCode.keycode_EXCLAIM;
      case SDL_KeyCode.SDLK_QUOTEDBL:
        return KeyCode.keycode_QUOTEDBL;
      case SDL_KeyCode.SDLK_HASH:
        return KeyCode.keycode_HASH;
      case SDL_KeyCode.SDLK_PERCENT:
        return KeyCode.keycode_PERCENT;
      case SDL_KeyCode.SDLK_DOLLAR:
        return KeyCode.keycode_DOLLAR;
      case SDL_KeyCode.SDLK_AMPERSAND:
        return KeyCode.keycode_AMPERSAND;
      case SDL_KeyCode.SDLK_QUOTE:
        return KeyCode.keycode_QUOTE;
      case SDL_KeyCode.SDLK_LEFTPAREN:
        return KeyCode.keycode_LEFTPAREN;
      case SDL_KeyCode.SDLK_RIGHTPAREN:
        return KeyCode.keycode_RIGHTPAREN;
      case SDL_KeyCode.SDLK_ASTERISK:
        return KeyCode.keycode_ASTERISK;
      case SDL_KeyCode.SDLK_PLUS:
        return KeyCode.keycode_PLUS;
      case SDL_KeyCode.SDLK_COMMA:
        return KeyCode.keycode_COMMA;
      case SDL_KeyCode.SDLK_MINUS:
        return KeyCode.keycode_MINUS;
      case SDL_KeyCode.SDLK_PERIOD:
        return KeyCode.keycode_PERIOD;
      case SDL_KeyCode.SDLK_SLASH:
        return KeyCode.keycode_SLASH;
      case SDL_KeyCode.SDLK_0:
        return KeyCode.keycode_0;
      case SDL_KeyCode.SDLK_1:
        return KeyCode.keycode_1;
      case SDL_KeyCode.SDLK_2:
        return KeyCode.keycode_2;
      case SDL_KeyCode.SDLK_3:
        return KeyCode.keycode_3;
      case SDL_KeyCode.SDLK_4:
        return KeyCode.keycode_4;
      case SDL_KeyCode.SDLK_5:
        return KeyCode.keycode_5;
      case SDL_KeyCode.SDLK_6:
        return KeyCode.keycode_6;
      case SDL_KeyCode.SDLK_7:
        return KeyCode.keycode_7;
      case SDL_KeyCode.SDLK_8:
        return KeyCode.keycode_8;
      case SDL_KeyCode.SDLK_9:
        return KeyCode.keycode_9;
      case SDL_KeyCode.SDLK_COLON:
        return KeyCode.keycode_COLON;
      case SDL_KeyCode.SDLK_SEMICOLON:
        return KeyCode.keycode_SEMICOLON;
      case SDL_KeyCode.SDLK_LESS:
        return KeyCode.keycode_LESS;
      case SDL_KeyCode.SDLK_EQUALS:
        return KeyCode.keycode_EQUALS;
      case SDL_KeyCode.SDLK_GREATER:
        return KeyCode.keycode_GREATER;
      case SDL_KeyCode.SDLK_QUESTION:
        return KeyCode.keycode_QUESTION;
      case SDL_KeyCode.SDLK_AT:
        return KeyCode.keycode_AT;
      case SDL_KeyCode.SDLK_LEFTBRACKET:
        return KeyCode.keycode_LEFTBRACKET;
      case SDL_KeyCode.SDLK_BACKSLASH:
        return KeyCode.keycode_BACKSLASH;
      case SDL_KeyCode.SDLK_RIGHTBRACKET:
        return KeyCode.keycode_RIGHTBRACKET;
      case SDL_KeyCode.SDLK_CARET:
        return KeyCode.keycode_CARET;
      case SDL_KeyCode.SDLK_UNDERSCORE:
        return KeyCode.keycode_UNDERSCORE;
      case SDL_KeyCode.SDLK_BACKQUOTE:
        return KeyCode.keycode_BACKQUOTE;
      case SDL_KeyCode.SDLK_a:
        return KeyCode.keycode_a;
      case SDL_KeyCode.SDLK_b:
        return KeyCode.keycode_b;
      case SDL_KeyCode.SDLK_c:
        return KeyCode.keycode_c;
      case SDL_KeyCode.SDLK_d:
        return KeyCode.keycode_d;
      case SDL_KeyCode.SDLK_e:
        return KeyCode.keycode_e;
      case SDL_KeyCode.SDLK_f:
        return KeyCode.keycode_f;
      case SDL_KeyCode.SDLK_g:
        return KeyCode.keycode_g;
      case SDL_KeyCode.SDLK_h:
        return KeyCode.keycode_h;
      case SDL_KeyCode.SDLK_i:
        return KeyCode.keycode_i;
      case SDL_KeyCode.SDLK_j:
        return KeyCode.keycode_j;
      case SDL_KeyCode.SDLK_k:
        return KeyCode.keycode_k;
      case SDL_KeyCode.SDLK_l:
        return KeyCode.keycode_l;
      case SDL_KeyCode.SDLK_m:
        return KeyCode.keycode_m;
      case SDL_KeyCode.SDLK_n:
        return KeyCode.keycode_n;
      case SDL_KeyCode.SDLK_o:
        return KeyCode.keycode_o;
      case SDL_KeyCode.SDLK_p:
        return KeyCode.keycode_p;
      case SDL_KeyCode.SDLK_q:
        return KeyCode.keycode_q;
      case SDL_KeyCode.SDLK_r:
        return KeyCode.keycode_r;
      case SDL_KeyCode.SDLK_s:
        return KeyCode.keycode_s;
      case SDL_KeyCode.SDLK_t:
        return KeyCode.keycode_t;
      case SDL_KeyCode.SDLK_u:
        return KeyCode.keycode_u;
      case SDL_KeyCode.SDLK_v:
        return KeyCode.keycode_v;
      case SDL_KeyCode.SDLK_w:
        return KeyCode.keycode_w;
      case SDL_KeyCode.SDLK_x:
        return KeyCode.keycode_x;
      case SDL_KeyCode.SDLK_y:
        return KeyCode.keycode_y;
      case SDL_KeyCode.SDLK_z:
        return KeyCode.keycode_z;
      case SDL_KeyCode.SDLK_CAPSLOCK:
        return KeyCode.keycode_CAPSLOCK;
      case SDL_KeyCode.SDLK_F1:
        return KeyCode.keycode_F1;
      case SDL_KeyCode.SDLK_F2:
        return KeyCode.keycode_F2;
      case SDL_KeyCode.SDLK_F3:
        return KeyCode.keycode_F3;
      case SDL_KeyCode.SDLK_F4:
        return KeyCode.keycode_F4;
      case SDL_KeyCode.SDLK_F5:
        return KeyCode.keycode_F5;
      case SDL_KeyCode.SDLK_F6:
        return KeyCode.keycode_F6;
      case SDL_KeyCode.SDLK_F7:
        return KeyCode.keycode_F7;
      case SDL_KeyCode.SDLK_F8:
        return KeyCode.keycode_F8;
      case SDL_KeyCode.SDLK_F9:
        return KeyCode.keycode_F9;
      case SDL_KeyCode.SDLK_F10:
        return KeyCode.keycode_F10;
      case SDL_KeyCode.SDLK_F11:
        return KeyCode.keycode_F11;
      case SDL_KeyCode.SDLK_F12:
        return KeyCode.keycode_F12;
      case SDL_KeyCode.SDLK_PRINTSCREEN:
        return KeyCode.keycode_PRINTSCREEN;
      case SDL_KeyCode.SDLK_SCROLLLOCK:
        return KeyCode.keycode_SCROLLLOCK;
      case SDL_KeyCode.SDLK_PAUSE:
        return KeyCode.keycode_PAUSE;
      case SDL_KeyCode.SDLK_INSERT:
        return KeyCode.keycode_INSERT;
      case SDL_KeyCode.SDLK_HOME:
        return KeyCode.keycode_HOME;
      case SDL_KeyCode.SDLK_PAGEUP:
        return KeyCode.keycode_PAGEUP;
      case SDL_KeyCode.SDLK_DELETE:
        return KeyCode.keycode_DELETE;
      case SDL_KeyCode.SDLK_END:
        return KeyCode.keycode_END;
      case SDL_KeyCode.SDLK_PAGEDOWN:
        return KeyCode.keycode_PAGEDOWN;
      case SDL_KeyCode.SDLK_RIGHT:
        return KeyCode.keycode_RIGHT;
      case SDL_KeyCode.SDLK_LEFT:
        return KeyCode.keycode_LEFT;
      case SDL_KeyCode.SDLK_DOWN:
        return KeyCode.keycode_DOWN;
      case SDL_KeyCode.SDLK_UP:
        return KeyCode.keycode_UP;
      case SDL_KeyCode.SDLK_NUMLOCKCLEAR:
        return KeyCode.keycode_NUMLOCKCLEAR;
      case SDL_KeyCode.SDLK_KP_DIVIDE:
        return KeyCode.keycode_KP_DIVIDE;
      case SDL_KeyCode.SDLK_KP_MULTIPLY:
        return KeyCode.keycode_KP_MULTIPLY;
      case SDL_KeyCode.SDLK_KP_MINUS:
        return KeyCode.keycode_KP_MINUS;
      case SDL_KeyCode.SDLK_KP_PLUS:
        return KeyCode.keycode_KP_PLUS;
      case SDL_KeyCode.SDLK_KP_ENTER:
        return KeyCode.keycode_KP_ENTER;
      case SDL_KeyCode.SDLK_KP_1:
        return KeyCode.keycode_KP_1;
      case SDL_KeyCode.SDLK_KP_2:
        return KeyCode.keycode_KP_2;
      case SDL_KeyCode.SDLK_KP_3:
        return KeyCode.keycode_KP_3;
      case SDL_KeyCode.SDLK_KP_4:
        return KeyCode.keycode_KP_4;
      case SDL_KeyCode.SDLK_KP_5:
        return KeyCode.keycode_KP_5;
      case SDL_KeyCode.SDLK_KP_6:
        return KeyCode.keycode_KP_6;
      case SDL_KeyCode.SDLK_KP_7:
        return KeyCode.keycode_KP_7;
      case SDL_KeyCode.SDLK_KP_8:
        return KeyCode.keycode_KP_8;
      case SDL_KeyCode.SDLK_KP_9:
        return KeyCode.keycode_KP_9;
      case SDL_KeyCode.SDLK_KP_0:
        return KeyCode.keycode_KP_0;
      case SDL_KeyCode.SDLK_KP_PERIOD:
        return KeyCode.keycode_KP_PERIOD;
      case SDL_KeyCode.SDLK_APPLICATION:
        return KeyCode.keycode_APPLICATION;
      case SDL_KeyCode.SDLK_POWER:
        return KeyCode.keycode_POWER;
      case SDL_KeyCode.SDLK_KP_EQUALS:
        return KeyCode.keycode_KP_EQUALS;
      case SDL_KeyCode.SDLK_F13:
        return KeyCode.keycode_F13;
      case SDL_KeyCode.SDLK_F14:
        return KeyCode.keycode_F14;
      case SDL_KeyCode.SDLK_F15:
        return KeyCode.keycode_F15;
      case SDL_KeyCode.SDLK_F16:
        return KeyCode.keycode_F16;
      case SDL_KeyCode.SDLK_F17:
        return KeyCode.keycode_F17;
      case SDL_KeyCode.SDLK_F18:
        return KeyCode.keycode_F18;
      case SDL_KeyCode.SDLK_F19:
        return KeyCode.keycode_F19;
      case SDL_KeyCode.SDLK_F20:
        return KeyCode.keycode_F20;
      case SDL_KeyCode.SDLK_F21:
        return KeyCode.keycode_F21;
      case SDL_KeyCode.SDLK_F22:
        return KeyCode.keycode_F22;
      case SDL_KeyCode.SDLK_F23:
        return KeyCode.keycode_F23;
      case SDL_KeyCode.SDLK_F24:
        return KeyCode.keycode_F24;
      case SDL_KeyCode.SDLK_EXECUTE:
        return KeyCode.keycode_EXECUTE;
      case SDL_KeyCode.SDLK_HELP:
        return KeyCode.keycode_HELP;
      case SDL_KeyCode.SDLK_MENU:
        return KeyCode.keycode_MENU;
      case SDL_KeyCode.SDLK_SELECT:
        return KeyCode.keycode_SELECT;
      case SDL_KeyCode.SDLK_STOP:
        return KeyCode.keycode_STOP;
      case SDL_KeyCode.SDLK_AGAIN:
        return KeyCode.keycode_AGAIN;
      case SDL_KeyCode.SDLK_UNDO:
        return KeyCode.keycode_UNDO;
      case SDL_KeyCode.SDLK_CUT:
        return KeyCode.keycode_CUT;
      case SDL_KeyCode.SDLK_COPY:
        return KeyCode.keycode_COPY;
      case SDL_KeyCode.SDLK_PASTE:
        return KeyCode.keycode_PASTE;
      case SDL_KeyCode.SDLK_FIND:
        return KeyCode.keycode_FIND;
      case SDL_KeyCode.SDLK_MUTE:
        return KeyCode.keycode_MUTE;
      case SDL_KeyCode.SDLK_VOLUMEUP:
        return KeyCode.keycode_VOLUMEUP;
      case SDL_KeyCode.SDLK_VOLUMEDOWN:
        return KeyCode.keycode_VOLUMEDOWN;
      case SDL_KeyCode.SDLK_KP_COMMA:
        return KeyCode.keycode_KP_COMMA;
      case SDL_KeyCode.SDLK_KP_EQUALSAS400:
        return KeyCode.keycode_KP_EQUALSAS400;
      case SDL_KeyCode.SDLK_ALTERASE:
        return KeyCode.keycode_ALTERASE;
      case SDL_KeyCode.SDLK_SYSREQ:
        return KeyCode.keycode_SYSREQ;
      case SDL_KeyCode.SDLK_CANCEL:
        return KeyCode.keycode_CANCEL;
      case SDL_KeyCode.SDLK_CLEAR:
        return KeyCode.keycode_CLEAR;
      case SDL_KeyCode.SDLK_PRIOR:
        return KeyCode.keycode_PRIOR;
      case SDL_KeyCode.SDLK_RETURN2:
        return KeyCode.keycode_RETURN2;
      case SDL_KeyCode.SDLK_SEPARATOR:
        return KeyCode.keycode_SEPARATOR;
      case SDL_KeyCode.SDLK_OUT:
        return KeyCode.keycode_OUT;
      case SDL_KeyCode.SDLK_OPER:
        return KeyCode.keycode_OPER;
      case SDL_KeyCode.SDLK_CLEARAGAIN:
        return KeyCode.keycode_CLEARAGAIN;
      case SDL_KeyCode.SDLK_CRSEL:
        return KeyCode.keycode_CRSEL;
      case SDL_KeyCode.SDLK_EXSEL:
        return KeyCode.keycode_EXSEL;
      case SDL_KeyCode.SDLK_KP_00:
        return KeyCode.keycode_KP_00;
      case SDL_KeyCode.SDLK_KP_000:
        return KeyCode.keycode_KP_000;
      case SDL_KeyCode.SDLK_THOUSANDSSEPARATOR:
        return KeyCode.keycode_THOUSANDSSEPARATOR;
      case SDL_KeyCode.SDLK_DECIMALSEPARATOR:
        return KeyCode.keycode_DECIMALSEPARATOR;
      case SDL_KeyCode.SDLK_CURRENCYUNIT:
        return KeyCode.keycode_CURRENCYUNIT;
      case SDL_KeyCode.SDLK_CURRENCYSUBUNIT:
        return KeyCode.keycode_CURRENCYSUBUNIT;
      case SDL_KeyCode.SDLK_KP_LEFTPAREN:
        return KeyCode.keycode_KP_LEFTPAREN;
      case SDL_KeyCode.SDLK_KP_RIGHTPAREN:
        return KeyCode.keycode_KP_RIGHTPAREN;
      case SDL_KeyCode.SDLK_KP_LEFTBRACE:
        return KeyCode.keycode_KP_LEFTBRACE;
      case SDL_KeyCode.SDLK_KP_RIGHTBRACE:
        return KeyCode.keycode_KP_RIGHTBRACE;
      case SDL_KeyCode.SDLK_KP_TAB:
        return KeyCode.keycode_KP_TAB;
      case SDL_KeyCode.SDLK_KP_BACKSPACE:
        return KeyCode.keycode_KP_BACKSPACE;
      case SDL_KeyCode.SDLK_KP_A:
        return KeyCode.keycode_KP_A;
      case SDL_KeyCode.SDLK_KP_B:
        return KeyCode.keycode_KP_B;
      case SDL_KeyCode.SDLK_KP_C:
        return KeyCode.keycode_KP_C;
      case SDL_KeyCode.SDLK_KP_D:
        return KeyCode.keycode_KP_D;
      case SDL_KeyCode.SDLK_KP_E:
        return KeyCode.keycode_KP_E;
      case SDL_KeyCode.SDLK_KP_F:
        return KeyCode.keycode_KP_F;
      case SDL_KeyCode.SDLK_KP_XOR:
        return KeyCode.keycode_KP_XOR;
      case SDL_KeyCode.SDLK_KP_POWER:
        return KeyCode.keycode_KP_POWER;
      case SDL_KeyCode.SDLK_KP_PERCENT:
        return KeyCode.keycode_KP_PERCENT;
      case SDL_KeyCode.SDLK_KP_LESS:
        return KeyCode.keycode_KP_LESS;
      case SDL_KeyCode.SDLK_KP_GREATER:
        return KeyCode.keycode_KP_GREATER;
      case SDL_KeyCode.SDLK_KP_AMPERSAND:
        return KeyCode.keycode_KP_AMPERSAND;
      case SDL_KeyCode.SDLK_KP_DBLAMPERSAND:
        return KeyCode.keycode_KP_DBLAMPERSAND;
      case SDL_KeyCode.SDLK_KP_VERTICALBAR:
        return KeyCode.keycode_KP_VERTICALBAR;
      case SDL_KeyCode.SDLK_KP_DBLVERTICALBAR:
        return KeyCode.keycode_KP_DBLVERTICALBAR;
      case SDL_KeyCode.SDLK_KP_COLON:
        return KeyCode.keycode_KP_COLON;
      case SDL_KeyCode.SDLK_KP_HASH:
        return KeyCode.keycode_KP_HASH;
      case SDL_KeyCode.SDLK_KP_SPACE:
        return KeyCode.keycode_KP_SPACE;
      case SDL_KeyCode.SDLK_KP_AT:
        return KeyCode.keycode_KP_AT;
      case SDL_KeyCode.SDLK_KP_EXCLAM:
        return KeyCode.keycode_KP_EXCLAM;
      case SDL_KeyCode.SDLK_KP_MEMSTORE:
        return KeyCode.keycode_KP_MEMSTORE;
      case SDL_KeyCode.SDLK_KP_MEMRECALL:
        return KeyCode.keycode_KP_MEMRECALL;
      case SDL_KeyCode.SDLK_KP_MEMCLEAR:
        return KeyCode.keycode_KP_MEMCLEAR;
      case SDL_KeyCode.SDLK_KP_MEMADD:
        return KeyCode.keycode_KP_MEMADD;
      case SDL_KeyCode.SDLK_KP_MEMSUBTRACT:
        return KeyCode.keycode_KP_MEMSUBTRACT;
      case SDL_KeyCode.SDLK_KP_MEMMULTIPLY:
        return KeyCode.keycode_KP_MEMMULTIPLY;
      case SDL_KeyCode.SDLK_KP_MEMDIVIDE:
        return KeyCode.keycode_KP_MEMDIVIDE;
      case SDL_KeyCode.SDLK_KP_PLUSMINUS:
        return KeyCode.keycode_KP_PLUSMINUS;
      case SDL_KeyCode.SDLK_KP_CLEAR:
        return KeyCode.keycode_KP_CLEAR;
      case SDL_KeyCode.SDLK_KP_CLEARENTRY:
        return KeyCode.keycode_KP_CLEARENTRY;
      case SDL_KeyCode.SDLK_KP_BINARY:
        return KeyCode.keycode_KP_BINARY;
      case SDL_KeyCode.SDLK_KP_OCTAL:
        return KeyCode.keycode_KP_OCTAL;
      case SDL_KeyCode.SDLK_KP_DECIMAL:
        return KeyCode.keycode_KP_DECIMAL;
      case SDL_KeyCode.SDLK_KP_HEXADECIMAL:
        return KeyCode.keycode_KP_HEXADECIMAL;
      case SDL_KeyCode.SDLK_LCTRL:
        return KeyCode.keycode_LCTRL;
      case SDL_KeyCode.SDLK_LSHIFT:
        return KeyCode.keycode_LSHIFT;
      case SDL_KeyCode.SDLK_LALT:
        return KeyCode.keycode_LALT;
      case SDL_KeyCode.SDLK_LGUI:
        return KeyCode.keycode_LGUI;
      case SDL_KeyCode.SDLK_RCTRL:
        return KeyCode.keycode_RCTRL;
      case SDL_KeyCode.SDLK_RSHIFT:
        return KeyCode.keycode_RSHIFT;
      case SDL_KeyCode.SDLK_RALT:
        return KeyCode.keycode_RALT;
      case SDL_KeyCode.SDLK_RGUI:
        return KeyCode.keycode_RGUI;
      case SDL_KeyCode.SDLK_MODE:
        return KeyCode.keycode_MODE;
      case SDL_KeyCode.SDLK_AUDIONEXT:
        return KeyCode.keycode_AUDIONEXT;
      case SDL_KeyCode.SDLK_AUDIOPREV:
        return KeyCode.keycode_AUDIOPREV;
      case SDL_KeyCode.SDLK_AUDIOSTOP:
        return KeyCode.keycode_AUDIOSTOP;
      case SDL_KeyCode.SDLK_AUDIOPLAY:
        return KeyCode.keycode_AUDIOPLAY;
      case SDL_KeyCode.SDLK_AUDIOMUTE:
        return KeyCode.keycode_AUDIOMUTE;
      case SDL_KeyCode.SDLK_MEDIASELECT:
        return KeyCode.keycode_MEDIASELECT;
      case SDL_KeyCode.SDLK_WWW:
        return KeyCode.keycode_WWW;
      case SDL_KeyCode.SDLK_MAIL:
        return KeyCode.keycode_MAIL;
      case SDL_KeyCode.SDLK_CALCULATOR:
        return KeyCode.keycode_CALCULATOR;
      case SDL_KeyCode.SDLK_COMPUTER:
        return KeyCode.keycode_COMPUTER;
      case SDL_KeyCode.SDLK_AC_SEARCH:
        return KeyCode.keycode_AC_SEARCH;
      case SDL_KeyCode.SDLK_AC_HOME:
        return KeyCode.keycode_AC_HOME;
      case SDL_KeyCode.SDLK_AC_BACK:
        return KeyCode.keycode_AC_BACK;
      case SDL_KeyCode.SDLK_AC_FORWARD:
        return KeyCode.keycode_AC_FORWARD;
      case SDL_KeyCode.SDLK_AC_STOP:
        return KeyCode.keycode_AC_STOP;
      case SDL_KeyCode.SDLK_AC_REFRESH:
        return KeyCode.keycode_AC_REFRESH;
      case SDL_KeyCode.SDLK_AC_BOOKMARKS:
        return KeyCode.keycode_AC_BOOKMARKS;
      case SDL_KeyCode.SDLK_BRIGHTNESSDOWN:
        return KeyCode.keycode_BRIGHTNESSDOWN;
      case SDL_KeyCode.SDLK_BRIGHTNESSUP:
        return KeyCode.keycode_BRIGHTNESSUP;
      case SDL_KeyCode.SDLK_DISPLAYSWITCH:
        return KeyCode.keycode_DISPLAYSWITCH;
      case SDL_KeyCode.SDLK_KBDILLUMTOGGLE:
        return KeyCode.keycode_KBDILLUMTOGGLE;
      case SDL_KeyCode.SDLK_KBDILLUMDOWN:
        return KeyCode.keycode_KBDILLUMDOWN;
      case SDL_KeyCode.SDLK_KBDILLUMUP:
        return KeyCode.keycode_KBDILLUMUP;
      case SDL_KeyCode.SDLK_EJECT:
        return KeyCode.keycode_EJECT;
      case SDL_KeyCode.SDLK_SLEEP:
        return KeyCode.keycode_SLEEP;
      case SDL_KeyCode.SDLK_APP1:
        return KeyCode.keycode_APP1;
      case SDL_KeyCode.SDLK_APP2:
        return KeyCode.keycode_APP2;
      case SDL_KeyCode.SDLK_AUDIOREWIND:
        return KeyCode.keycode_AUDIOREWIND;
      case SDL_KeyCode.SDLK_AUDIOFASTFORWARD:
        return KeyCode.keycode_AUDIOFASTFORWARD;
      default:
        throw SdlError(this, 'Unknown keycode.');
    }
  }
}
